## Learning python script

In [1]:
import numpy as np
import pandas as pd
x2 = [[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]]

x3 = np.array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [2]:
print(x3)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [3]:
x3[:2, :3]  # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [4]:
x = np.array([[1, 2, 7], [7, 7, 1]]);
y = np.array([[6, 5, 5], [0, 6, 1]])

In [5]:
print(x-y)

[[-5 -3  2]
 [ 7  1  0]]


In [6]:
print(x+y)

[[ 7  7 12]
 [ 7 13  2]]


In [7]:
print(x/y)

[[0.16666667 0.4        1.4       ]
 [       inf 1.16666667 1.        ]]


C:\Users\ganga\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [8]:
x <- 12
y <- 4
x %% y

SyntaxError: invalid syntax (<ipython-input-8-015c3062c63c>, line 3)

In [ ]:
mood <- c("happy", "unhappy", "unhappy", "happy")
factor(mood, levels = c("unhappy", "happy"), ordered = mood)

In [ ]:
c(3, 1, 2, 1) * c(1, 2, 1, 1)

In [ ]:
def solve(numheads,numlegs):
    ns='No solutions!'
    for i in range(numheads+1):
        j=numheads-i
        if 2*i+4*j==numlegs:
            return i,j
    return ns,ns
numheads=35
numlegs=94
solutions=solve(numheads,numlegs)
print(solutions)

In [ ]:
print(list(permutations([1,2,3])))

In [ ]:
from itertools import permutations
x = [1,2,3]
print(list(permutations(x, 2)))

In [ ]:
print(list(permutations([1,2,3])))

In [ ]:
s=[H1e2l3l4o5w6o7r8l9d]
s = s[::2]
print(s)

##   Remove duplicate values from list.

In [ ]:
li=[12,24,35,24,88,120,155,88,120,155]
def removeDuplicate( li ):
    newli=[]
    seen = set()
    for item in li:
        if item not in seen:
            seen.add( item )
            newli.append(item)

    return newli

print (removeDuplicate(li))


## Intersection operation from both list 
#### Use set() and "&=" to do set intersection operation.

In [ ]:
set1=set([1,3,6,78,35,55,120])
set2=set([12,24,35,24,88,120,155,55])
set1 &= set2
list = (set1)
print(list)

## Use list's remove method to delete a value.

In [ ]:
list = set([12,24,35,24,88,120,155,55])
list = [x for x in list if x!=24]
print(list)

## Use list comprehension to delete a bunch of element from a list. Use enumerate() to get (index, value) tuple. ( remove 0th,3rd,4th position)

In [ ]:
list1 = [12,24,35,24,88,120,155,55]
list1 = [x for (i,x) in enumerate(list1) if i not in (0,3,4)]
print(list1)
## -----------------------------------------------
list2 = [12,24,35,24,88,120,155,55]
list2 = [x for (i,x) in enumerate(list2) if i%2 != 0]
print(list2)

###   By using list comprehension, please write a program generate a 3*5*8 3D array whose each element is 0.

In [ ]:
array1 = [[ [0 for col in range(8)] for col in range(5)] for row in range(3)]
print (array1)


###  By using list comprehension, please write a program to print the list after removing delete numbers which are divisible by 5 and 7 in list.

In [ ]:
x = [12,24,35,70,88,120,155,55,60,65]
list = [x for x in list if x%5 != 0 and x%7 != 0]
print(list)

### Write a program which will find all such numbers which are divisible by 7 but are not a multiple of 5

In [ ]:
l=[]  # strat with null
for i in range(200, 321):
    if (i%7==0) and (i%5!=0):
        l.append(str(i))

print (','.join(l))

### ???

In [ ]:
%debug

In [ ]:
li = [34,67,55,33,12,98]
#values=li
#l=values.split(",")
#t=tuple(l)
#print (l)
#print (t)

#lst = ['a', 'b']
tup = tuple(li)
#li.append('a')
another_tuple = tuple(li)
print(another_tuple)

In [ ]:
import math
c=50
h=30
value = list([34,67,55,33,12,98])
items=[x for x in raw_input().split(',')]
for d in items:
    value.append(str(int(round(math.sqrt(2*c*float(d)/h)))))

print (','.join(value))

In [ ]:
if 0!=-1:
    print ("Good!")

while 0!=-1:
    print ("BWAHAHAHA")

for i in range(1,10):
    print (i)
    
try:
    print (blah)
except NameError:
    print ("Blah is not defined")

In [ ]:
f = open('my_file.dat')
data = f.readfile()
print('Loaded data')

In [ ]:
try:
    f = open('my_file.dat')
    f.readfile()
    print('Loaded data')
except:
    print('Data not loaded')

In [ ]:
try:
    file = open('my_file.dat')
    data = file.readfile()
    print('Data Loaded')
except FileNotFoundError:
    print('This file doesn\'t exist')

In [ ]:
try:
    file = open('my_file.dat')
    data = file.readfile()
    print('Data Loaded')
except:
    file = open('my_file.dat', 'w')
    print('File created')

In [ ]:
filename = 'my_data.dat'
try:
    file = open(filename)
    data = file.readfile()
except FileNotFoundError:
    file = open(filename, 'w')
    print('Created file')
except AttributeError:
    print('Attribute Error')

In [ ]:
filename = 'my_data.dat'
try:
    file = open(filename)
    data = file.read()
    important_data = data[0]
except FileNotFoundError:
    file = open(filename, 'w')
    print('Created file')
except AttributeError:
    print('Attribute Error')
except:
    print('Unhandled exception')

In [ ]:
filename = 'my_data.dat'

try:
    file = open(filename)
    data = file.read()
    important_data = data[0]
except Exception as e:
    print('Unhandled exception')
    if isinstance(e, IndexError):
        print(e)
        data = 'Information'
        important_data = data[0]

print(important_data)

In [ ]:
filename = 'my_data.dat'

try:
    file = open(filename)
except FileNotFoundError:
    print('File not found, creating one')
    file = open(filename, 'w')
else:
    new_file = open(new_filename)
    data = new_file.read()
finally:
    file.close()

In [ ]:
from exceptions import NonPositiveError
from tools import average

try:
    avg = average(1, -2)
except NonPositiveError:
    avg = 0

In [ ]:
a = 'hello';
lia = list(a)  # ['h', 'e', 'l', 'l', 'o'] 
lis = set(a)   # {'o', 'e', 'l', 'h'} 
lit = tuple(a) # ('h', 'e', 'l', 'l', 'o') 
print(lia)
print(lis)
print(lit)

In [ ]:
mytuple = list(("apple", "banana", "cherry"))

for x1 in mytuple:
  print(x1)

mytuple = list(("apple"))
for x in mytuple:
    print(x)

In [ ]:
thistuple = tuple(("apple", "banana", "cherry"))

for y in thistuple:
 print(y)

In [ ]:
class MyNumbers:
  def __iter__(num):
    num.a = 1
    return num

  def __next__(self):
    if self.a <= 12:
      x = self.a
      self.a += 1
      return x
    else:
      raise StopIteration

myclass = MyNumbers()
myiter = iter(myclass)

for x in myiter:
  print(x)

In [ ]:
def my_function(x):
  return 5 * x

print(my_function(5))
print(my_function(10))
print(my_function(15))

In [ ]:
x=lambda a, b, c, d: a*b+c-d
print(x(2,3,9,3))

In [ ]:
import datetime

x = datetime.datetime.now()

print(x.strftime("%x"))

In [ ]:
f = open("\PycharmProjects\demofile.txt", "r")
#print(f.read())
#print(f.read(5))
for x in f:
    print(x)

In [ ]:
f = open("\PycharmProjects\demofile.txt", "a")
f.write("Now the file has one more line!")

In [ ]:
f = open("\PycharmProjects\demofile.txt", "r")
print(f.read())

In [ ]:
f = open("myfile.txt", "x")

In [ ]:
f = open("myfile.txt", "a")
f.write("Now the file has one more line!")

In [ ]:
f = open("myfile.txt", "r")
print(f.read())

In [ ]:
import numpy as np
m = np.array([4, 2, 6])
n = 2
print(m / n)

In [ ]:
import numpy as np
np.array([1, 0, 1]) + np.array([2, 4, 6])

In [ ]:
import numpy as np
x = np.array([3, 4, True, False, "5.2"])
print(x)

In [ ]:
x = [11, 12, 13, 14]
y = x
y[2:4] = [15, 16]
print(x)

In [ ]:
def main():
  print ("Hello World!")
  
if __name__== "__main__":
  main()

print ("Guru99")

In [ ]:
f = 101;
print(f)

def somefunction():
   # global f
   # print(f)
    f = "text f value display in code"
    print(f)

somefunction()
print(f)

In [ ]:
x = "Hello World!"
print(x[:6]) 
print(x[0:6] + "Guru99")

In [ ]:
class Length:

    __metric = {"mm" : 0.001, "cm" : 0.01, "m" : 1, "km" : 1000,
                "in" : 0.0254, "ft" : 0.3048, "yd" : 0.9144,
                "mi" : 1609.344 }
    
    def __init__(self, value, unit = "m" ):
        self.value = value
        self.unit = unit
    
    def Converse2Metres(self):
        return self.value * Length.__metric[self.unit]
    
    def __add__(self, other):
        l = self.Converse2Metres() + other.Converse2Metres()
        return Length(l / Length.__metric[self.unit], self.unit )
    
    def __str__(self):
        return str(self.Converse2Metres())
    
    def __repr__(self):
        return "Length(" + str(self.value) + ", '" + self.unit + "')"

if __name__ == "__main__":
    x = Length(4)
    print(x)
    y = eval(repr(x))

    z = Length(4.5, "yd") + Length(1)
    print(repr(z))
    print(z)